[window]

opacity = 0.9

padding.x = 10
padding.y = 10

decorations = "None"
decorations_theme_variant = "Dark"

[font]

normal.family = "CaskaydiaCove Nerd Font"
bold.family = "CaskaydiaCove Nerd Font"
italic.family = "CaskaydiaCove Nerd Font"
bold_italic.family = "CaskaydiaCove Nerd Font"

# size = 15.0
